name: 'Terraform Infastrucutre Deployment with Checkov Scan'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  AWS_REGION: us-east-1
  TF_VAR_region: us-east-1

jobs:
  build:
    name: Build and Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.6

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      # Run Checkov on each module directory
      - name: Checkov - Static Code Analysis on EC2 Module
        run: checkov -d modules/ec2 || true

      - name: Checkov - Static Code Analysis on Route Table Module
        run: checkov -d modules/route_table || true

      - name: Checkov - Static Code Analysis on VPC Module
        run: checkov -d modules/vpc || true

      - name: Checkov - Static Code Analysis on NAT Gateway Module
        run: checkov -d modules/nat_gateway || true

      - name: Checkov - Static Code Analysis on Security Group Module
        run: checkov -d modules/security_group || true

      - name: Checkov - Static Code Analysis on Subnet Module
        run: checkov -d modules/subnet || true

      # Initialize Terraform in the root directory
      - name: Download tfplan file from S3
        run: aws s3 cp s3://group21-secret-bucket/tfplan .

      - name: Terraform Apply
        id: apply
        run: terraform apply tfplan
